// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGE.Data;

#nullable disable

namespace SGE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716234309_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGE.Models.Entities.AsignacionVotante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion");

                    b.Property<int>("MovilizadorId")
                        .HasColumnType("integer")
                        .HasColumnName("movilizador_id");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("MovilizadorId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("asignaciones_votantes");
                });

            modelBuilder.Entity("SGE.Models.Entities.Movilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("patente");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<int>("ReferenteId")
                        .HasColumnType("integer")
                        .HasColumnName("referente_id");

                    b.Property<string>("Vehiculo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehiculo");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex("ReferenteId");

                    b.ToTable("movilizadores");
                });

            modelBuilder.Entity("SGE.Models.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido_nombre");

                    b.Property<string>("Cambio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cambio");

                    b.Property<string>("Circuito")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("circuito");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<long>("Dni")
                        .HasColumnType("bigint")
                        .HasColumnName("dni");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("domicilio");

                    b.Property<string>("DomicilioEscuela")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("domicilio_escuela");

                    b.Property<string>("Escuela")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("escuela");

                    b.Property<int?>("IdSeccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_seccion");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidad");

                    b.Property<string>("LocalidadEscuela")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("localidad_escuela");

                    b.Property<int?>("Mesa")
                        .HasColumnType("integer")
                        .HasColumnName("mesa");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int?>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("personas");
                });

            modelBuilder.Entity("SGE.Models.Entities.Referente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("referentes");
                });

            modelBuilder.Entity("SGE.Models.Entities.AsignacionVotante", b =>
                {
                    b.HasOne("SGE.Models.Entities.Movilizador", "Movilizador")
                        .WithMany("Votantes")
                        .HasForeignKey("MovilizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGE.Models.Entities.Persona", "Persona")
                        .WithOne("AsignacionVotante")
                        .HasForeignKey("SGE.Models.Entities.AsignacionVotante", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movilizador");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SGE.Models.Entities.Movilizador", b =>
                {
                    b.HasOne("SGE.Models.Entities.Persona", "Persona")
                        .WithOne("Movilizador")
                        .HasForeignKey("SGE.Models.Entities.Movilizador", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGE.Models.Entities.Referente", "Referente")
                        .WithMany("Movilizadores")
                        .HasForeignKey("ReferenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Referente");
                });

            modelBuilder.Entity("SGE.Models.Entities.Referente", b =>
                {
                    b.HasOne("SGE.Models.Entities.Persona", "Persona")
                        .WithOne("Referente")
                        .HasForeignKey("SGE.Models.Entities.Referente", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SGE.Models.Entities.Movilizador", b =>
                {
                    b.Navigation("Votantes");
                });

            modelBuilder.Entity("SGE.Models.Entities.Persona", b =>
                {
                    b.Navigation("AsignacionVotante");

                    b.Navigation("Movilizador");

                    b.Navigation("Referente");
                });

            modelBuilder.Entity("SGE.Models.Entities.Referente", b =>
                {
                    b.Navigation("Movilizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
